version: "3.9"

services:
  api:
    tty: true
    stdin_open: true
    build:
      context: .
    container_name: tasks-api
    ports:
      - '3000:3000'
      - '8800:8800'
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: 'development'
