version: "3.9"

services:
  db:
    image: 'postgres:18'
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    command: -p 5432
    volumes:
      - ./.docker/pgsql-data:/var/lib/postgresql/data
      - ./.docker/shared_db:/home
      - ./docker-script/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env

  api:
    tty: true
    stdin_open: true
    build:
      context: .
    container_name: tasks-api
    ports:
      - '3000:3000'
      - '8800:8800'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      RAILS_ENV: '${RAILS_ENV}'
    env_file: .env
