default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: <%= ENV.fetch('DATABASE_NAME') { 'tasks-development' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'tasks' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { '5432' } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'tasks' } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_TEST_NAME') { 'tasks-test' } %>

homolog:
  <<: *default

production:
  <<: *default
