default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  database: db/development.sqlite3
  host: 'localhost'
  password: 'tasks'
  port: 5432
  username: 'tasks'

development:
  <<: *default

test:
  <<: *default
  database: 'tasks-test'

homolog:
  <<: *default

production:
  <<: *default
